---

- name: Создать роль replica
  postgresql_user:
    name: replica
    password: "{{ password_replica }}"
    role_attr_flags: LOGIN,REPLICATION
  environment:
    PGOPTIONS: "-c password_encryption=md5"

- name: Создать запись в hba
  pg_hba:
    dest: /var/lib/pgsql/{{ postgresql_version }}/data/pg_hba.conf
    contype: host
    users: replica
    source: "{{ ip_replica }}"/32
    databases: replication
    method: md5