---

- name: Копирование бинарника на целевой хост
  copy:
    src: files/pgscv
    dest: /usr/bin/pgscv
    owner: root
    group: root
    mode: '755'

- name: Установка pgscv.yaml
  template:
    src: templates/pgscv.yaml.j2
    dest: /etc/pgscv.yaml
    mode: '644'
    owner: root
    group: root

- name: Установка pgscv.yaml
  template:
    src: templates/pgscv.service.j2
    dest: /etc/systemd/system/pgscv.service
    mode: '644'
    owner: root
    group: root

- name: Включить демон и добавить в автозагрузку
  systemd:
    name: pgscv
    state: started
    enabled: yes
    daemon_reload: yes