---

#- name: Установка репозитория для expect OEL8
#  shell: "wget https://repofiles.repo.corp.tander.ru/repofiles/yum/OEL8/oracle-linux-ol8.repo -O /etc/yum.repos.d/oracle-linux-ol8.repo"

- name: "Stage 5: install DSAA-repo"
  yum_repository:
    name: "DSSA-yum-packages"
    description: "DSSA-yum-packages"
    file: "DSSA-packages"
    baseurl: "https://repo.corp.tander.ru/repository/DSSA-yum-packages/"
    gpgcheck: false
    enabled: true
    async: true

- name: Установка пакетов DSSA/Networker
  yum:
    name:
      - lgtoclnt
      - lgtoman 
      - lgtoxtdclnt 
      - lgtonmda
      - DDBoostFS
      - expect
    state: latest

- name: Запуск службы Networker
  systemd:
    name: networker
    state: started
    enabled: yes

- name: Конфигурирование lockbox (используется модуль expect)
  ansible.builtin.script: files/expect.sh

- name: Конфигурирование lockbox (используется модуль expect)
  ansible.builtin.script: files/chmod.sh


- name: Создание директории для конфигурации Networker
  file:
    path: /database/any/networker
    state: directory

- name: Установка backup.sh
  template:
    src: templates/backup.sh.j2
    dest: /database/any/networker/backup.sh
    mode: '700'
    owner: postgres
    group: postgres

- name: Установка backup.sh
  template:
    src: templates/backup.cfg.j2
    dest: /database/any/networker/backup.cfg
    mode: '700'
    owner: postgres
    group: postgres

