---

- name: Установка пакетов
  yum:
    name:
      - "/database/oracle-instantclient19.9-basic-19.9.0.0.0-1.x86_64.rpm"
      - "/database/oracle-instantclient19.9-devel-19.9.0.0.0-1.x86_64.rpm"
      - "postgresql{{ postgresql_version }}-devel"
      - "gcc"
    state: present

- name: Владелец  каталога /usr/pgsql
  file:
    path: /usr/pgsql-14/
    state: directory
    owner: postgres
    group: postgres
    mode: '0755'
    recurse: yes

- name: Установить окружение в bash_profile
  lineinfile:
    path: /var/lib/pgsql/.bash_profile
    line: "{{ item.line }}"
  loop:
    - { line: 'PATH=$PATH:/usr/pgsql-14/bin' }
    - { line: 'export PATH' }
    - { line: 'export LD_LIBRARY_PATH=/usr/lib/oracle/19.9/client64/lib' }
    - { line: 'export ORACLE_HOME=/usr/lib/oracle/19.9/client64' }

- name: Установить окружение в bash_profile
  lineinfile:
    path: /home/loshakov_ma/.bash_profile
    line: "{{ item.line }}"
  loop:
    - { line: 'PATH=$PATH:/usr/pgsql-14/bin' }
    - { line: 'export PATH' }
    - { line: 'export LD_LIBRARY_PATH=/usr/lib/oracle/19.9/client64/lib' }
    - { line: 'export ORACLE_HOME=/usr/lib/oracle/19.9/client64' }



- name: Make/Make install oracle_fdw
  make:
    chdir: /database/oracle_fdw-ORACLE_FDW_2_4_0
#    target: all
  remote_user: postgres

- name: Make/Make install oracle_fdw
  make:
    chdir: /database/oracle_fdw-ORACLE_FDW_2_4_0
    target: install
  remote_user: postgres

- name: Установить расширение oracle_fdw
  postgresql_ext:
    name: oracle_fdw
    db: "{{ dbname }}"
    state: present

