---

- name: Копирование файла функции на целевой хост
  file:
    path: /database/installsys_install_realese_function.sql
    state: absent

- name: Копирование файлов install на целевой хост
  file:
    path: /database/install
    state: absent
