---

- name: Выдать привилегии пользователю install на схему install
  postgresql_privs:
    db: "{{ dbname }}"
    state: present
    privs: CREATE,USAGE
    schema: install
    role: install
    objs: ALL_IN_SCHEMA

- name: Выдать привилегии пользователю installsys на схему installsys
  postgresql_privs:
    db: "{{ dbname }}"
    state: present
    privs: CREATE,USAGE
    schema: installsys 
    role: installsys
    objs: ALL_IN_SCHEMA     

- name: Сделать пользователя install владельцем схемы install
  postgresql_owner:
    db: "{{ dbname }}"
    new_owner: install
    obj_name: install
    obj_type: schema

- name: Сделать пользователя installsys владельцем схемы installsys
  postgresql_owner:
    db: "{{ dbname }}"
    new_owner: installsys
    obj_name: installsys
    obj_type: schema

- name: Назначаем роль на select всех таблиц в БД для install
  postgresql_membership:
    group: pg_read_all_data
    target_role: install
    state: present

- name: Назначаем привилегии по умолчанию для пользователя install на все создаваемые в будущем объекты в схеме install на тот случай если объекты будут создаваться не под пользователем install
  postgresql_privs:
    db: "{{ dbname }}"
    schema: install
    privs: ALL
    state: present
    type: default_privs
    role: install
    objs: tables,sequences,types

- name: Назначаем привилегии отдельно для системной таблицы inf_schema
  postgresql_privs:
    db: "{{ dbname }}"
    schema: information_schema
    privs: ALL
    state: present
    role: install
    objs: routines

- name: Выдать привилегию usage пользователю install на схему installsys
  postgresql_privs:
    db: "{{ dbname }}"
    state: present
    priv:  USAGE
    schema: installsys
    role: install
    objs: ALL_IN_SCHEMA

- name: Создать функцию installsys.install_realese(varchar) для временной выдачи install роли installsys во время поставки
  postgresql_query:
    db: "{{ dbname }}"
    path_to_script: /database/installsys_install_realese_function.sql

- name: Выдать привилегию execute пользователю install на функцию installsys.install_realese(varchar)
  postgresql_privs:
    db: "{{ dbname }}"
    type: function
    state: present
    privs: execute
    roles: install
    objs: install_realese(varchar)
    schema: installsys

- name: Отозвать привилегию execute у пользователя public на функцию installsys.install_realese(varchar)
  postgresql_privs:
    db: "{{ dbname }}"
    type: function
    state: absent
    privs: execute
    roles: public
    objs: install_realese(varchar)
    schema: installsys

- name: Установка подсистемы INSTALL
  postgresql_db:
    name: "{{ dbname }}"
    state: dump
    login_user: install
    login_password: install
    target: /database/install/install.sql
