---

- name: Установка обслуживания БД Analyze каждый день в 01:00
  cron:
    name: Analyze every day
    hour: '1'
    user: postgres
    job: "/usr/pgsql-{{ postgresql_version }}/bin/vacuumdb  -U postgres -a -Z -j 4 "

- name: Установка обслуживания БД Vacuum + Analyze + Freeze каждую субботу в 01:00
  cron:
    name: Vacuum + Analyze + Freeze every week
    hour: '1'
    weekday: '6'
    user: postgres
    job: "/usr/pgsql-{{ postgresql_version }}/bin/vacuumdb  -U postgres -a -z -F -j 4"
